# Much of this script was adapted from astropy/astropy, dfm/george.

language: python


python:
  - 3.6
  - 3.7
env:
  - TEST_ARGS=
matrix:
  include:
    - python: 3.5.2
      env: TEST_ARGS=tests/test_imports.py
dist: xenial
sudo: true

cache:
  pip: true
  directories:
    - tests/data

before_install:
  - pip install -U pipenv

install:
  - pipenv install --deploy -d --python $TRAVIS_PYTHON_VERSION

before_script:
  - pipenv run python setup.py build_ext --inplace

script:
  - pipenv run pytest $TEST_ARGS
