language: python
dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8-dev
  - nightly

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode9.4
      python: 3.6
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6
    - os: osx
      osx_image: xcode10.2
      python: 3.7
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7
    - os: windows
      python: 3.6
      language: shell
      env: 
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH 
        - TRAVIS_PYTHON_VERSION=3.6
      before_install: 
        - choco install python --version 3.6.0
        - python -m pip install -U pip
        - python -m pip install -U pipenv
    - os: windows 
      python: 3.7
      language: shell
      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH 
        - TRAVIS_PYTHON_VERSION=3.7
      before_install: 
        - choco install python --version 3.7.0
        - python -m pip install -U pip
        - python -m pip install -U pipenv
  allow_failures:
    - os: windows
    - python: 3.8-dev
    - python: nightly

cache:
  pip: true
  directories:
    - tests/data

# This will only run for the linux and macOS versions
before_install:
  - pip3 install -U pip
  - pip3 install -U pipenv

install:
  # This will make sure we can install via pyproject.toml/setup.py
  - pip3 install . 
  # But still use pipenv for the locked dependencies
  - pipenv install -d --python $TRAVIS_PYTHON_VERSION

script:
  - pipenv run black --check .
  - pipenv run pytest --cov=Starfish --benchmark-skip

after_success:
  - coveralls
