language: python
dist: xenial

python:
  - 3.6
  - 3.7
  - nightly

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode10.2
      env: TRAVIS_PYTHON_VERSION=3.7
      language: generic
    - os: windows 
      python: 3.7
      language: shell
      env: 
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH  
        - TRAVIS_PYTHON_VERSION=3.7
      before_install: 
        - choco install python --version 3.7.1
        - python -m pip install -U pipenv
  allow_failures:
    - os: windows
    - python: nightly

cache:
  pip: true
  directories:
    - tests/data

# This will only run for the linux and macOS versions
before_install:
  - pip install -U pipenv

install:
  - pipenv install -d --python $TRAVIS_PYTHON_VERSION

script:
  - pipenv run pytest

after_success:
  - coveralls
