language: python

matrix:
  include:
  - os: linux
    python: 3.6
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
  - os: osx
    osx_image: xcode10.2
    env: TRAVIS_PYTHON_VERSION=3.7
    language: generic   
  allow_failures:
  - os: linux
    python: nightly
    dist: xenial
    sudo: true
  - os: windows 
    python: 3.7
    language: shell
    before_install: 
      - choco install python --version 3.7.1
      - python -m pip install -U pipenv
    env: 
      - PATH=/c/Python37:/c/Python37/Scripts:$PATH  
      - TRAVIS_PYTHON_VERSION=3.7
  fast_finish: true

cache:
  pip: true
  directories:
    - tests/data

# This will only run for the linux and macOS versions
before_install:
  - pip install -U pipenv

install:
  - pipenv install --deploy -d --python $TRAVIS_PYTHON_VERSION

script:
  - pipenv run pytest

after_success:
  - coveralls
