# Data parameters
orders : [21,22,23]

# MCMC parameters
ndim : 15
nwalkers : 150
burn_in : 2000
iterations : 2000
MPI : False
threads : 4
output_dir : output

# Params local for testing
# threads : 4
# burn_in : 1
# iterations : 10

