# Data parameters
orders : [21,22,23]

# MCMC parameters
ndim : 15
nwalkers : 128
burn_in : 5000
iterations : 5000
MPI : False
threads : 64
output_dir : output

# Params local for testing
# threads : 4
# burn_in : 1
# iterations : 10

