# Data parameters
orders : [22]

# MCMC parameters
ndim : 7
nwalkers : 128
burn_in : 200
iterations : 200
MPI : True
threads : 64
output_dir : output

# Params local for testing
# threads : 4
# burn_in : 1
# iterations : 10

