# Output parameters
name : GMAur/order_22/sivia/PHOENIX  #internal tests

Comments: >
  Using Kurucz grid on GMAur

# Data parameters
#orders : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50]
#orders : [4,5,6,7,8,9,10,11,12,13,14,15,16,19,20,21,22,23,24,25,26,27,28,30,31,32,33,34,35,42,45]
#orders : [21,22,23,24,25]
orders : [21]
dataset: GMAur/GMAur_2013-11-10_10h16m22s_cb.spec.flux

# Model parameters
#lnprob : lnprob
lnprob : lnprob_mixed


sigmac : 0.05
sigmac0 : 0.1

# Limit the range of grid space that is read in. Note that routine will load in only gridpoints that are
# within the bounds. T_eff is generally spaced in 100K, logg is spaced in 0.5, and metallicity is -0.5, 0.0, and 0.5.
grid_params :
    temp_range : [3500, 6000]
    logg_range : [2.5, 5.0]
    Z_range : [-0.5, 0.5] #this is necessary to load any metallicity at all. Could also limit to just negative or positive.

# MCMC parameters
nparams : 7 # these do not include nuisance parameters c0, c1, c2...
nwalkers : 64
ncoeff : 4 #order Chebyshev polynomial
burn_in : 4000
iterations : 2000
MPI : True
threads : 4
output_dir : output
plots : True

# Interactive parameters
pnwalkers : 24
pburn_in : 20
piterations : 100

grid : PHOENIX

# Where to start the MCMC chains, assuming uniform distribution over the range of parameters
walker_ranges :
    temp : [3600,4500]
    logg : [3.1, 4.1]
    Z : [-0.45, 0.0]
    vsini : [16, 22.0]
    vz : [1, 4]
    Av : [0.0, 0.2]
    flux_factor : [5e-21, 7e-21] #PHOENIX
    #flux_factor : [1e-26, 2e-26] #kurucz
    c0 : [0.9, 1.1]
    cs : [-0.02, 0.02]

AvOff : True #Turn Av fitting off?

# Params local for testing
# threads : 4
# burn_in : 1
# iterations : 10

